#!/usr/bin/env sh

greenclip print | grep . | rofi -dmenu -i -theme ~/.config/rofi/reverse.rasi -lines "8" -width 1300 -yoffset "-340" -no-fixed-num-lines -p ' Clipboard ' | xargs -r -d'\n' -I '{}' greenclip print '{}'
