#!/usr/bin/env sh
sleep 3s # wait

mpdas & # what am I listening(last.fm)

mpc update # update Database

mpc load "$(mpc lsplaylists | sort | uniq | shuf -n 1)" # load random playlist

mpc volume 70 # set volumn

mpc random true # Randomise

mpc play;mpc pause #start and stop to get things going
